### ISSUE TITLE
entities unavailable after configuration

### ISSUE THREAD

**Issue by jonathansimmons** [gurumitts/pylutron-caseta#42]
I recently installed this plugin in my home assistant. While all of the entities show up, they are all listed as unavailable. 

The setup is pretty straightforward and succeeded at all steps so I'm unsure what next steps to take to sort through why they aren't working. 

Has anyone seen this issue before 

Here is an image of the devices. Note the items listed as fans are just luton switches labelled as fans NOT the official Lutron fan device. 
![Screen+Shot+2020-03-05+at+8 55 52+AM](https://user-images.githubusercontent.com/945202/75993516-32aa2f80-5ebf-11ea-9c3e-366f579cf146.png)

**Comment by mdonoughe** [comment]
Do they not work or just show as unavailable on that screen?

Do you have any of these 4-button remotes? http://www.lutron.com/en-US/Products/Pages/Components/PicoWirelessController/Models.aspx#4-Button

Do you have errors in the Home Assistant log?

**Comment by swails** [comment]
Scene picos (pico remotes with custom engravings) will break the existing integration by crashing the pylutron_caseta library shortly after devices and app-configured scenes are discovered.

#41 fixes that (as well as adding support for occupancy/vacancy sensors if you have any of those).

**Comment by jonathansimmons** [comment]
No they do not work. The overview page list them too, but they are "unavailable" there as well.

I actually don't have any of the 4 button pico's. Weirder still is that I had this setup working previously but my home assistant computer's drive failed and I didn't have a backup. So this is a fresh install but I've had this plugin working with my hardware before. 

Here are a couple more screenshots: 

![Screen Shot 2020-03-10 at 9 48 52 PM](https://user-images.githubusercontent.com/945202/76377547-2851c080-6319-11ea-80d0-4e4317c3f6aa.png)

There are a couple of python errors but I can't tell if they would be related: 
![Screen Shot 2020-03-10 at 9 47 13 PM](https://user-images.githubusercontent.com/945202/76377584-3f90ae00-6319-11ea-9a47-377463641000.png)

**Comment by swails** [comment]
The not authorized message seems to suggest that the ssh certificates are no longer recognized as valid.

**Comment by jonathansimmons** [comment]
So I've rebuilt the certs just to be sure but that hasn't helped any. 

I reloaded that logs an noticed an error about it not having pylutron. So I installed that and tried to setup the plugin again. Same issue. 

Next I tried removing the unavailable entities but that seems to make the lutron setup disappear altogether. It only come back if I put the plugin setting in the configuration.yaml incorrectly (wrong indentation), restart the server, then fix the indentation and restart the server again. 

However, this simple put back the entities. They are still unavailable. 

The big thing I noticed tonight though is that the only entities listed are switches. I have over 15 dimmers that just don't show up at all. So something is up. The only thing different from this setup is that I have the abode plugin installed. I'm tempted to remove it and try again.

**Comment by jonathansimmons** [comment]
Ok, I just realized I was missing something about a notification after the server started. 

The notification says that the lutron_caseta.light could not be setup and to check my configuration. However, when I go look at the entities the switches are there and WORKING! however, I'm for whatever reason missing all the lights.  

So as of right now this is my config file, can someone tell me what I've done wrong: 

```

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lutron_caseta:
  host: 192.168.7.27
  keyfile: caseta.key
  certfile: caseta.crt
  ca_certs: caseta-bridge.crt

```

If I move the lutron config up under default config, where I thought it should be, that is when the switches become unavailable. 

Why don't lights work though.
